# Generated by Django 5.2 on 2026-01-13 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_domain_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='core.website'),
        ),
    ]
