# Generated by Django 5.2 on 2026-01-21 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_domain_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Productos', 'Productos'), ('Contacto', 'Contacto'), ('Nosotros', 'Nosotros'), ('Servicios', 'Servicios')], max_length=25)),
                ('is_Active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_links', to='core.website')),
            ],
        ),
    ]
