# Generated by Django 5.2 on 2026-03-03 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_must_change_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headerlinks',
            old_name='is_Active',
            new_name='is_active',
        ),
    ]
