# Generated by Django 5.2 on 2026-01-13 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_domain_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=250, null=True)),
                ('subheadline', models.CharField(blank=True, max_length=450, null=True)),
                ('imageUrl', models.CharField()),
                ('textCta', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
