# Generated by Django 5.2 on 2026-01-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0002_herosection_order_herosection_urlcta_aboutsection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutsection',
            options={'verbose_name': 'Home - about Section', 'verbose_name_plural': 'Home - about Section'},
        ),
        migrations.AlterModelOptions(
            name='benefitssection',
            options={'verbose_name': 'Home - Benefits Section', 'verbose_name_plural': 'Home - Benefits Section'},
        ),
        migrations.AlterModelOptions(
            name='finalctasection',
            options={'verbose_name': 'Home - CTA Section', 'verbose_name_plural': 'Home - CTA Section'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Home - Hero Section', 'verbose_name_plural': 'Home - Hero Section'},
        ),
        migrations.AlterModelOptions(
            name='howitworkssection',
            options={'verbose_name': 'Home - How it works Section', 'verbose_name_plural': 'Home - How it works Section'},
        ),
        migrations.AlterModelOptions(
            name='servicesection',
            options={'verbose_name': 'Home - Services Section', 'verbose_name_plural': 'Home - Services Section'},
        ),
        migrations.AlterModelOptions(
            name='testimonialsection',
            options={'verbose_name': 'Home - Testimonial Section', 'verbose_name_plural': 'Home - Testimonial Section'},
        ),
        migrations.AddField(
            model_name='benefitssection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
