# Generated by Django 5.2 on 2026-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_aboutsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
