# Generated by Django 5.2 on 2026-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0004_benefit_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='servicesection',
            name='url',
            field=models.CharField(default=''),
        ),
    ]
