# Generated by Django 5.2 on 2026-01-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0005_servicesection_subtitle_servicesection_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='tagline',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
