# Generated by Django 5.2 on 2026-01-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0006_rename_tagline_service_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
