# Generated by Django 5.2 on 2026-01-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0007_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url_text',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
