# Generated by Django 5.2 on 2026-01-20 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0008_service_url_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutsection',
            name='title',
            field=models.CharField(default=''),
        ),
        migrations.CreateModel(
            name='AboutMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(default='', max_length=150)),
                ('text', models.CharField(default='', max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='showcase.aboutsection')),
            ],
        ),
    ]
