# Generated by Django 5.2 on 2026-01-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0010_tertimonialmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalctasection',
            name='subheadline',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
