# Generated by Django 5.2 on 2026-01-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0011_finalctasection_subheadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='highlight_word',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
