# Generated by Django 5.2 on 2026-01-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0012_herosection_highlight_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='imageAlt',
            field=models.CharField(default=''),
        ),
    ]
