# Generated by Django 5.2 on 2026-01-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0013_herosection_imagealt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
