# Generated by Django 5.2 on 2026-02-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0014_testimonial_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='imageUrl',
            field=models.CharField(max_length=500),
        ),
    ]
