# Generated by Django 5.2 on 2026-02-25 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0018_rename_service_to_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsection',
            options={'verbose_name': 'Home - Products Section', 'verbose_name_plural': 'Home - Products Section'},
        ),
        migrations.AlterField(
            model_name='product',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='showcase.productsection'),
        ),
        migrations.AlterField(
            model_name='productsection',
            name='title',
            field=models.CharField(default='Productos', max_length=200),
        ),
    ]
