# Generated by Django 5.2 on 2026-02-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_must_change_password'),
        ('showcase', '0020_aboutdifferentiatorssection_aboutdifferentiator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsGridSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('collection_label', models.CharField(default='Colección 2024', help_text='Etiqueta de colección que aparece sobre el título de cada producto.', max_length=100)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsIntroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.website')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=500)),
                ('image_alt', models.CharField(default='', max_length=200)),
                ('for_who', models.TextField(help_text="Texto del bloque '¿Para quién es?' de cada producto.")),
                ('price', models.CharField(help_text="Precio orientativo, p.ej. 'Desde 850€'.", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='showcase.productsgridsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductsItemInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='includes', to='showcase.productsitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
