# Generated by Django 5.2 on 2026-02-27 00:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_must_change_password'),
        ('showcase', '0021_productsgridsection_productsintrosection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsitem',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='productsitem',
            options={},
        ),
        migrations.RenameField(
            model_name='productsitem',
            old_name='for_who',
            new_name='forWho',
        ),
        migrations.RenameField(
            model_name='productsitem',
            old_name='image_alt',
            new_name='imageAlt',
        ),
        migrations.RenameField(
            model_name='productsitem',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.RemoveField(
            model_name='productsitem',
            name='price',
        ),
        migrations.AddField(
            model_name='productsitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 27, 0, 13, 3, 996871, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productsitem',
            name='website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.website'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProductsGridSection',
        ),
    ]
