# Generated by Django 5.2 on 2026-03-02 22:22

import apps.showcase.models.contact
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0023_contactformsection_contactformsubjectoption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsection',
            name='form_fields',
            field=models.JSONField(default=list, help_text='Array de campos a mostrar: name, email, subject', validators=[apps.showcase.models.contact.validate_allowed_fields]),
        ),
    ]
